import type { OpeningBookEntry } from "./openingBook";

// Generated by scripts/generate-very-hard-book.ts; provenance {"generator":"linith-classical-book-1:native:sha256-5fcb7525c578833d65219d792825ef4e00ad26ed06641b63dd87bac1a2e0e794","artifactFingerprint":"sha256-5fcb7525c578833d65219d792825ef4e00ad26ed06641b63dd87bac1a2e0e794","positionsConsidered":8,"acceptedEntries":8,"rejectedEntries":0}
const GENERATED_VERY_HARD_OPENING_BOOK: readonly OpeningBookEntry[] = [
  {
    "schema": 1,
    "key": "linith-book-v1:1:1:0000000000000000000000000000000000000000000000010000200000000000000000000000000000000000000000000000",
    "action": {
      "type": "swan",
      "r": 4,
      "c": 6
    },
    "score": 5557,
    "confidence": 0.9800000000000001,
    "verification": {
      "agreements": 3,
      "independentRuns": 3,
      "minCompletedDepth": 5,
      "tacticalDepth": 3,
      "minNodeBudget": 1000000
    },
    "generator": "linith-classical-book-1:native:sha256-5fcb7525c578833d65219d792825ef4e00ad26ed06641b63dd87bac1a2e0e794"
  },
  {
    "schema": 1,
    "key": "linith-book-v1:1:1:0000000000000000000000000000000000000000000000100000000000000002000000000000000000000000000000000000",
    "action": {
      "type": "swan",
      "r": 4,
      "c": 5
    },
    "score": 5909,
    "confidence": 0.9800000000000001,
    "verification": {
      "agreements": 3,
      "independentRuns": 3,
      "minCompletedDepth": 5,
      "tacticalDepth": 3,
      "minNodeBudget": 1000000
    },
    "generator": "linith-classical-book-1:native:sha256-5fcb7525c578833d65219d792825ef4e00ad26ed06641b63dd87bac1a2e0e794"
  },
  {
    "schema": 1,
    "key": "linith-book-v1:1:1:0000000000000000000000000000000000000000000002000000000000000001000000000000000000000000000000000000",
    "action": {
      "type": "swan",
      "r": 5,
      "c": 3
    },
    "score": 4900,
    "confidence": 0.9800000000000001,
    "verification": {
      "agreements": 3,
      "independentRuns": 3,
      "minCompletedDepth": 5,
      "tacticalDepth": 3,
      "minNodeBudget": 1000000
    },
    "generator": "linith-classical-book-1:native:sha256-5fcb7525c578833d65219d792825ef4e00ad26ed06641b63dd87bac1a2e0e794"
  },
  {
    "schema": 1,
    "key": "linith-book-v1:1:1:0000000000000000000000000001000000000000000000000000000000000000000000002000000000000000000000000000",
    "action": {
      "type": "swan",
      "r": 2,
      "c": 6
    },
    "score": 5404,
    "confidence": 0.9800000000000001,
    "verification": {
      "agreements": 3,
      "independentRuns": 3,
      "minCompletedDepth": 5,
      "tacticalDepth": 3,
      "minNodeBudget": 1000000
    },
    "generator": "linith-classical-book-1:native:sha256-5fcb7525c578833d65219d792825ef4e00ad26ed06641b63dd87bac1a2e0e794"
  },
  {
    "schema": 1,
    "key": "linith-book-v1:1:1:0000000000000000000000000003000003022000000003000000000000030001000000303300000000000000000000000030",
    "action": {
      "type": "swan",
      "r": 5,
      "c": 3
    },
    "score": -985,
    "confidence": 0.9800000000000001,
    "verification": {
      "agreements": 3,
      "independentRuns": 3,
      "minCompletedDepth": 5,
      "tacticalDepth": 3,
      "minNodeBudget": 1000000
    },
    "generator": "linith-classical-book-1:native:sha256-5fcb7525c578833d65219d792825ef4e00ad26ed06641b63dd87bac1a2e0e794"
  },
  {
    "schema": 1,
    "key": "linith-book-v1:1:1:0000000000000000000000032000300000000000030000000000000003003000003000030001000000000130300003000000",
    "action": {
      "type": "swan",
      "r": 6,
      "c": 5
    },
    "score": 9590,
    "confidence": 0.9800000000000001,
    "verification": {
      "agreements": 3,
      "independentRuns": 3,
      "minCompletedDepth": 5,
      "tacticalDepth": 3,
      "minNodeBudget": 1000000
    },
    "generator": "linith-classical-book-1:native:sha256-5fcb7525c578833d65219d792825ef4e00ad26ed06641b63dd87bac1a2e0e794"
  },
  {
    "schema": 1,
    "key": "linith-book-v1:1:1:0000000000000000000300000300000110000030000000003003032000000000000000000000000000000000300300000300",
    "action": {
      "type": "swan",
      "r": 3,
      "c": 3
    },
    "score": 11434,
    "confidence": 0.9800000000000001,
    "verification": {
      "agreements": 3,
      "independentRuns": 3,
      "minCompletedDepth": 5,
      "tacticalDepth": 3,
      "minNodeBudget": 1000000
    },
    "generator": "linith-classical-book-1:native:sha256-5fcb7525c578833d65219d792825ef4e00ad26ed06641b63dd87bac1a2e0e794"
  },
  {
    "schema": 1,
    "key": "linith-book-v1:1:1:0000000000000000033000000301000030000000000000000300000000003300030000302000000000000000003000000000",
    "action": {
      "type": "swan",
      "r": 3,
      "c": 7
    },
    "score": 4376,
    "confidence": 0.9800000000000001,
    "verification": {
      "agreements": 3,
      "independentRuns": 3,
      "minCompletedDepth": 5,
      "tacticalDepth": 3,
      "minNodeBudget": 1000000
    },
    "generator": "linith-classical-book-1:native:sha256-5fcb7525c578833d65219d792825ef4e00ad26ed06641b63dd87bac1a2e0e794"
  }
];

export const VERY_HARD_OPENING_BOOK: readonly OpeningBookEntry[] =
  Object.freeze(GENERATED_VERY_HARD_OPENING_BOOK);
