import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "../..");
const output = resolve(root, "src/renderer/game/veryHard/native/linith-core.wasm");
mkdirSync(dirname(output), { recursive: true });

const personalities = JSON.parse(
  readFileSync(resolve(root, "src/renderer/game/aiPersonalities.json"), "utf8")
);
const traitNames = [
  "freezeUrgency",
  "selfPreservation",
  "libertyBalance",
  "containment",
  "territory",
  "fragmentation",
  "development",
  "structure",
  "mobility"
];
const nativeNames = Object.fromEntries(traitNames.map((name) => [name, `personality${name[0].toUpperCase()}${name.slice(1)}`]));
const generated = [
  "// Generated from src/renderer/game/aiPersonalities.json by build-wasm.mjs.",
  "// Do not edit this file directly.",
  ""
];
for (const trait of traitNames) {
  generated.push(`export function ${nativeNames[trait]}(style: i32): f64 {`);
  for (let style = 1; style < personalities.length; style += 1) {
    const value = Number(personalities[style].traits?.[trait] ?? 0);
    generated.push(`  if (style == ${style}) return ${value.toFixed(6)};`);
  }
  generated.push("  return 0.0;", "}", "");
}
writeFileSync(resolve(here, "personality.generated.ts"), `${generated.join("\n")}\n`, "utf8");

const bundledNpx = resolve(dirname(process.execPath), "node_modules/npm/bin/npx-cli.js");
const executable = existsSync(bundledNpx) ? process.execPath : process.platform === "win32" ? "npx.cmd" : "npx";
const prefixArgs = existsSync(bundledNpx) ? [bundledNpx] : [];
const result = spawnSync(
  executable,
  [...prefixArgs, "--yes", "--package", "assemblyscript@0.28.20", "asc", "linith-core.ts", "--config", "asconfig.json", "--target", "release"],
  { cwd: here, stdio: "inherit", shell: process.platform === "win32" && !existsSync(bundledNpx) }
);
if (result.error) throw result.error;
if (result.status !== 0) process.exit(result.status ?? 1);
