// Generated from src/renderer/game/aiPersonalities.json by build-wasm.mjs.
// Do not edit this file directly.

export function personalityFreezeUrgency(style: i32): f64 {
  if (style == 1) return 0.250000;
  if (style == 2) return -0.100000;
  if (style == 3) return 1.700000;
  if (style == 4) return -0.300000;
  if (style == 5) return 0.200000;
  if (style == 6) return 0.000000;
  return 0.0;
}

export function personalitySelfPreservation(style: i32): f64 {
  if (style == 1) return 0.800000;
  if (style == 2) return 0.350000;
  if (style == 3) return 0.000000;
  if (style == 4) return 1.000000;
  if (style == 5) return 0.350000;
  if (style == 6) return 1.250000;
  return 0.0;
}

export function personalityLibertyBalance(style: i32): f64 {
  if (style == 1) return 0.450000;
  if (style == 2) return 0.150000;
  if (style == 3) return -0.100000;
  if (style == 4) return 1.550000;
  if (style == 5) return 0.150000;
  if (style == 6) return 0.250000;
  return 0.0;
}

export function personalityContainment(style: i32): f64 {
  if (style == 1) return 1.250000;
  if (style == 2) return 0.350000;
  if (style == 3) return 0.400000;
  if (style == 4) return 0.150000;
  if (style == 5) return 0.350000;
  if (style == 6) return 1.700000;
  return 0.0;
}

export function personalityTerritory(style: i32): f64 {
  if (style == 1) return 0.350000;
  if (style == 2) return 0.050000;
  if (style == 3) return -0.100000;
  if (style == 4) return 0.450000;
  if (style == 5) return 0.000000;
  if (style == 6) return 1.200000;
  return 0.0;
}

export function personalityFragmentation(style: i32): f64 {
  if (style == 1) return 0.150000;
  if (style == 2) return 1.700000;
  if (style == 3) return 0.000000;
  if (style == 4) return 0.100000;
  if (style == 5) return 0.100000;
  if (style == 6) return 0.100000;
  return 0.0;
}

export function personalityDevelopment(style: i32): f64 {
  if (style == 1) return 0.000000;
  if (style == 2) return 0.000000;
  if (style == 3) return 0.000000;
  if (style == 4) return 0.150000;
  if (style == 5) return 1.800000;
  if (style == 6) return -0.350000;
  return 0.0;
}

export function personalityStructure(style: i32): f64 {
  if (style == 1) return 0.700000;
  if (style == 2) return 0.250000;
  if (style == 3) return 0.200000;
  if (style == 4) return 0.100000;
  if (style == 5) return 0.000000;
  if (style == 6) return 1.600000;
  return 0.0;
}

export function personalityMobility(style: i32): f64 {
  if (style == 1) return 0.000000;
  if (style == 2) return 0.150000;
  if (style == 3) return -0.100000;
  if (style == 4) return 0.800000;
  if (style == 5) return 0.550000;
  if (style == 6) return -0.200000;
  return 0.0;
}

