<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<AssemblyName>Linith</AssemblyName>
	<RootNamespace>Linith</RootNamespace>
	<AssemblyTitle>Linith</AssemblyTitle>
	<Product>Linith</Product>
	<Description>Linith for Windows</Description>
	<FileVersion>0.232</FileVersion>
	<AssemblyVersion>0.232</AssemblyVersion>
  </PropertyGroup>
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- optional polish -->
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <PropertyGroup>
   <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
  </PropertyGroup>
  <PropertyGroup>
   <ApplicationIcon>Assets\linith_logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
   <Content Include="Assets\linith_logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3537.50" />
  </ItemGroup>

  <ItemGroup>
   <!-- Copy your HTML/assets -->
   <Content Include="Assets\**\*">
     <CopyToOutputDirectory>Always</CopyToOutputDirectory>
   </Content>

  <!-- Copy the Fixed WebView2 runtime -->
   <Content Include="WebView2Fixed\**\*">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </Content>
  </ItemGroup>
</Project>
